<?php

namespace MediaWiki\Extension\Workflows\MediaWiki\Maintenance;

use CommentStoreComment;
use LoggedUpdateMaintenance;
use MediaWiki\Extension\Workflows\Definition\Repository\IDefinitionRepository;
use MediaWiki\Extension\Workflows\MediaWiki\Content\TriggerDefinitionContent;
use MediaWiki\Extension\Workflows\Trigger\PageRelatedTrigger;
use MediaWiki\Extension\Workflows\TriggerRepo;
use MediaWiki\MediaWikiServices;
use MediaWiki\Revision\RevisionRecord;
use MediaWiki\Revision\SlotRecord;
use Title;
use User;
use WikiPage;

class CreateDefaultTriggersPage extends LoggedUpdateMaintenance {
	/**
	 * @inheritDoc
	 */
	protected function doDBUpdates() {
		$titleFactory = MediaWikiServices::getInstance()->getTitleFactory();
		$title = $titleFactory->makeTitle( NS_MEDIAWIKI, 'WorkflowTriggers' );

		if ( $title->exists() ) {
			$this->output( "...Page '{$title->getPrefixedDBkey()}' already exists\n" );
		} else {
			$this->createPage( $title );
		}
	}

	/**
	 * @param Title $title
	 * @throws \MWException
	 */
	private function createPage( Title $title ) {
		$this->output( "...Creating page '{$title->getPrefixedDBkey()}'..." );

		$wikipage = WikiPage::factory( $title );
		$content = $this->getDefaultContent();
		$comment = CommentStoreComment::newUnsavedComment( 'Autogenerated' );
		$updater = $wikipage->newPageUpdater( User::newSystemUser( 'Mediawiki default' ) );
		$updater->setContent( SlotRecord::MAIN, $content );
		$newRevision = $updater->saveRevision( $comment );
		if ( $newRevision instanceof RevisionRecord ) {
			$this->output( "done.\n" );
		} else {
			$this->output( "error.\n" );
		}
	}

	/**
	 * @inheritDoc
	 */
	protected function getUpdateKey() {
		return 'workflow-triggers-default-page';
	}

	/**
	 * @return TriggerDefinitionContent
	 */
	private function getDefaultContent() {
		$repositoryFactory = MediaWikiServices::getInstance()->getService( 'DefinitionRepositoryFactory' );
		/** @var TriggerRepo $triggerRepo */
		$triggerRepo = MediaWikiServices::getInstance()->getService( 'WorkflowTriggerRepo' );
		$triggers = [];
		foreach ( $repositoryFactory->getRepositoryKeys() as $key ) {
			/** @var IDefinitionRepository $repository */
			$repository = $repositoryFactory->getRepository( $key );
			$definitions = $repository->getAllKeys();
			foreach ( $definitions as $definition ) {
				$title = $repository->getDefinitionDisplayTitle( $definition );
				$triggerKey = $triggerRepo->generateTriggerKey( $title, 'manual' );
				$triggers[$triggerKey] = new PageRelatedTrigger(
					MediaWikiServices::getInstance()->getTitleFactory(),
					$triggerKey,
					$repository->getDefinitionDisplayTitle( $definition ),
					$repository->getDefinitionDescription( $definition ),
					'manual',
					$definition,
					$key,
					[], [], [],
					true
				);
			}
		}

		return new TriggerDefinitionContent( json_encode( $triggers ) );
	}
}
