-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/workflows_event.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/workflows_event (
  wfe_event_id BLOB NOT NULL, wfe_event_type BLOB DEFAULT NULL,
  wfe_aggregate_root_id BLOB NOT NULL,
  wfe_aggregate_root_version INTEGER DEFAULT NULL,
  wfe_time_of_recording BLOB NOT NULL,
  wfe_payload BLOB DEFAULT NULL
);
