-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/workflows_state.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/workflows_state (
  wfs_workflow_id BLOB NOT NULL,
  wfs_state BLOB NOT NULL,
  wfs_last_event BLOB NOT NULL,
  wfs_initiator INTEGER DEFAULT NULL,
  wfs_assignees CLOB DEFAULT NULL,
  wfs_touched BLOB DEFAULT NULL,
  wfs_started BLOB DEFAULT NULL,
  wfe_payload CLOB DEFAULT NULL,
  PRIMARY KEY(wfs_workflow_id)
);
