-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: db/workflows_state_assignees_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/workflows_state
  ADD wfs_assignees LONGTEXT DEFAULT NULL;
