-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/workflows_event.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE workflows_event (
  wfe_event_id TEXT NOT NULL, wfe_event_type TEXT DEFAULT NULL,
  wfe_aggregate_root_id TEXT NOT NULL,
  wfe_aggregate_root_version INT DEFAULT NULL,
  wfe_time_of_recording TEXT NOT NULL,
  wfe_payload TEXT DEFAULT NULL
);
