-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/workflows_state.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE workflows_state (
  wfs_workflow_id TEXT NOT NULL,
  wfs_state TEXT NOT NULL,
  wfs_last_event TEXT NOT NULL,
  wfs_initiator INT DEFAULT NULL,
  wfs_assignees TEXT DEFAULT NULL,
  wfs_touched TIMESTAMPTZ DEFAULT NULL,
  wfs_started TIMESTAMPTZ DEFAULT NULL,
  wfs_payload TEXT DEFAULT NULL,
  PRIMARY KEY(wfs_workflow_id)
);
